vich_uploader:
    db_driver: orm

    mappings:
        productImage:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        companyLogo:
            uri_prefix: /images/companies
            upload_destination: '%kernel.project_dir%/public/images/companies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        userImage:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
