version: "3.4"

services:
  php:
    hostname: toys-invoicers-php
    build:
      context: .docker/php
    restart: unless-stopped
    volumes:
      - .:/srv:cached

  nginx:
    hostname: toys-invoicers-nginx
    build:
      context: ./.docker/nginx
    volumes:
      - .:/srv:cached
    environment:
      fastcgi_pass: toys-invoicers-php:9000

  db:
    hostname: toys-invoicers-db
    image: postgres:16-alpine
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  database_data:
